// Generates the Octane brand mark (flame + turbine wheel) and all icon assets.
// Run: node scripts/gen-icons.mjs   (or: npm run gen:icons)
//
// Outputs:
//   components/runscope/logo.tsx        inline currentColor React component
//   public/icon.svg                     favicon (white mark on dark rounded tile)
//   build/octane.svg                    app-icon master (white mark on dark tile)
//   public/icon-dark-32x32.png          32px (tile)
//   public/icon-light-32x32.png         32px (tile)
//   public/apple-icon.png               180px (tile)
//   build/icon.png                      512px (tile) — used by electron-builder

import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import sharp from "sharp"

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, "..")

const VB = 100
const cx = 54
const cy = 62
const R = 30 // turbine outer radius
const HUB = 7
const BLADES = 11

const rad = (d) => (d * Math.PI) / 180
const pt = (a, r) => `${(cx + r * Math.cos(rad(a))).toFixed(2)},${(cy + r * Math.sin(rad(a))).toFixed(2)}`

// Curved compressor-style blades (filled wedges, swept for motion).
function blades() {
  let d = ""
  for (let i = 0; i < BLADES; i++) {
    const a = (360 / BLADES) * i - 90
    const inner = pt(a, HUB + 1)
    const tipOuter = pt(a + 17, R - 3)
    const tipInner = pt(a + 4, R - 3)
    const mid = pt(a + 2, (HUB + R) / 2)
    d += `M${inner} Q${mid} ${tipInner} L${tipOuter} Z `
  }
  return d.trim()
}

// Teardrop flame that hooks up and to the right, embracing the wheel.
const FLAME =
  "M40 70 " +
  "C14 52 22 14 50 4 " +
  "C66 -2 78 12 72 28 " +
  "C67 41 52 38 52 50 " +
  "C52 58 48 64 40 70 Z"

function mark(fill) {
  return [
    `<path d="${FLAME}" fill="${fill}"/>`,
    `<circle cx="${cx}" cy="${cy}" r="${R}" fill="none" stroke="${fill}" stroke-width="4.5"/>`,
    `<path d="${blades()}" fill="${fill}"/>`,
    `<circle cx="${cx}" cy="${cy}" r="${HUB}" fill="${fill}"/>`,
  ].join("\n    ")
}

// White mark on a dark rounded tile (visible on any background).
function tileSvg(size = VB) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${VB} ${VB}">
  <rect x="0" y="0" width="${VB}" height="${VB}" rx="22" fill="#0a0a0a"/>
  <g transform="translate(2 6) scale(0.92)">
    ${mark("#ffffff")}
  </g>
</svg>`
}

function logoTsx() {
  return `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
export function OctaneLogo({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 ${VB} ${VB}" className={className} fill="currentColor" aria-hidden="true">
    ${mark("currentColor")}
    </svg>
  )
}
`
}

// --- write vector sources ---
mkdirSync(join(root, "build"), { recursive: true })
mkdirSync(join(root, "public"), { recursive: true })
writeFileSync(join(root, "components/runscope/logo.tsx"), logoTsx())
writeFileSync(join(root, "public/icon.svg"), tileSvg())
writeFileSync(join(root, "build/octane.svg"), tileSvg())

// --- rasterize PNGs from the tile master ---
const master = Buffer.from(tileSvg(1024))
const out = [
  ["build/icon.png", 512],
  ["public/apple-icon.png", 180],
  ["public/icon-dark-32x32.png", 32],
  ["public/icon-light-32x32.png", 32],
]
await Promise.all(out.map(([file, size]) => sharp(master).resize(size, size).png().toFile(join(root, file))))

console.log("Octane icons generated:", out.map(([f]) => f).join(", "), "+ logo.tsx, icon.svg, octane.svg")
