// Generates the Octane brand mark (flame + turbine wheel) and all icon assets.
// Run: node scripts/gen-icons.mjs   (or: npm run gen:icons)
//
// Outputs:
//   components/runscope/logo.tsx        inline currentColor React component
//   public/icon.svg                     favicon (white mark on dark rounded tile)
//   build/octane.svg                    app-icon master (white mark on dark tile)
//   public/icon-dark-32x32.png          32px favicon
//   public/icon-light-32x32.png         32px favicon
//   public/icon-192.png                 192px PWA icon
//   public/icon-512.png                 512px PWA icon
//   public/maskable-192.png             192px maskable PWA icon
//   public/maskable-512.png             512px maskable PWA icon
//   public/apple-icon.png               180px Apple touch icon
//   public/og-image.png                 1200x630 social preview
//   build/icon.png                      512px Electron icon

import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import sharp from "sharp"

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, "..")

const VB = 100
const cx = 54
const cy = 62
const R = 30
const HUB = 7
const BLADES = 11

const rad = (d) => (d * Math.PI) / 180
const pt = (a, r) => `${(cx + r * Math.cos(rad(a))).toFixed(2)},${(cy + r * Math.sin(rad(a))).toFixed(2)}`

function blades() {
  let d = ""
  for (let i = 0; i < BLADES; i++) {
    const a = (360 / BLADES) * i - 90
    const inner = pt(a, HUB + 1)
    const tipOuter = pt(a + 17, R - 3)
    const tipInner = pt(a + 4, R - 3)
    const mid = pt(a + 2, (HUB + R) / 2)
    d += `M${inner} Q${mid} ${tipInner} L${tipOuter} Z `
  }
  return d.trim()
}

const FLAME =
  "M40 70 " +
  "C14 52 22 14 50 4 " +
  "C66 -2 78 12 72 28 " +
  "C67 41 52 38 52 50 " +
  "C52 58 48 64 40 70 Z"

function mark(fill, jsx = false) {
  const strokeWidth = jsx ? "strokeWidth" : "stroke-width"
  return [
    `<path d="${FLAME}" fill="${fill}"/>`,
    `<circle cx="${cx}" cy="${cy}" r="${R}" fill="none" stroke="${fill}" ${strokeWidth}="4.5"/>`,
    `<path d="${blades()}" fill="${fill}"/>`,
    `<circle cx="${cx}" cy="${cy}" r="${HUB}" fill="${fill}"/>`,
  ].join("\n    ")
}

function tileSvg(size = VB) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${VB} ${VB}">
  <rect x="0" y="0" width="${VB}" height="${VB}" rx="22" fill="#0a0a0a"/>
  <g transform="translate(2 6) scale(0.92)">
    ${mark("#ffffff")}
  </g>
</svg>`
}

function ogSvg() {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="#0a0a0a"/>
  <rect x="64" y="64" width="108" height="108" rx="24" fill="#111827"/>
  <g transform="translate(76 78) scale(0.86)">
    ${mark("#ffffff")}
  </g>
  <text x="64" y="308" fill="#ffffff" font-family="Arial, Helvetica, sans-serif" font-size="88" font-weight="700">Octane</text>
  <text x="70" y="374" fill="#8bd8ff" font-family="Arial, Helvetica, sans-serif" font-size="34" font-weight="600">ECU Telemetry Viewer</text>
  <text x="70" y="438" fill="#b7c1cc" font-family="Arial, Helvetica, sans-serif" font-size="26">Desktop and mobile CSV log analysis</text>
</svg>`
}

function logoTsx() {
  return `// AUTO-GENERATED by scripts/gen-icons.mjs - do not edit by hand.
export function OctaneLogo({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 ${VB} ${VB}" className={className} fill="currentColor" aria-hidden="true">
    ${mark("currentColor", true)}
    </svg>
  )
}
`
}

mkdirSync(join(root, "build"), { recursive: true })
mkdirSync(join(root, "public"), { recursive: true })
writeFileSync(join(root, "components/runscope/logo.tsx"), logoTsx())
writeFileSync(join(root, "public/icon.svg"), tileSvg())
writeFileSync(join(root, "build/octane.svg"), tileSvg())

const master = Buffer.from(tileSvg(1024))
const out = [
  ["build/icon.png", 512],
  ["public/apple-icon.png", 180],
  ["public/icon-192.png", 192],
  ["public/icon-512.png", 512],
  ["public/maskable-192.png", 192],
  ["public/maskable-512.png", 512],
  ["public/icon-dark-32x32.png", 32],
  ["public/icon-light-32x32.png", 32],
]

await Promise.all(out.map(([file, size]) => sharp(master).resize(size, size).png().toFile(join(root, file))))
await sharp(Buffer.from(ogSvg())).png({ compressionLevel: 9 }).toFile(join(root, "public/og-image.png"))

console.log("Octane icons generated:", out.map(([f]) => f).join(", "), "+ public/og-image.png, logo.tsx, icon.svg, octane.svg")
